# Generated by Django 4.1.7 on 2023-02-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='telegram_user_id',
            field=models.IntegerField(default=1, verbose_name='ID пользователя Telegram'),
            preserve_default=False,
        ),
    ]
