# Generated by Django 4.1.7 on 2023-02-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_registrationrequest_telegram_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('telegram_user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID пользователя Telegram')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='наименование')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('telegram_user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID пользователя Telegram')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='наименование')),
            ],
            options={
                'verbose_name': 'менеджер',
                'verbose_name_plural': 'менеджеры',
            },
        ),
        migrations.CreateModel(
            name='Subcontractor',
            fields=[
                ('telegram_user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID пользователя Telegram')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='наименование')),
                ('is_banned', models.BooleanField(db_index=True, default=False, verbose_name='заблокирован')),
            ],
            options={
                'verbose_name': 'подрядчик',
                'verbose_name_plural': 'подрядчики',
            },
        ),
    ]
