# Generated by Django 4.1.7 on 2023-02-24 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_client_manager_subcontractor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='описание')),
                ('time_estimation', models.TextField(blank=True, verbose_name='оценка времени')),
                ('status', models.CharField(choices=[('A1-UP', 'Необработанный'), ('B1-IP', 'В работе'), ('C1-CO', 'Выполнен'), ('D1-DE', 'Отклонен')], db_index=True, default='A1-UP', max_length=5, verbose_name='статус')),
                ('due_date', models.DateTimeField(db_index=True, verbose_name='срок')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создан в')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='изменен в')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tgbot.client', verbose_name='клиент')),
                ('subcontractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tgbot.subcontractor', verbose_name='подрядчик')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
