# Generated by Django 4.1.7 on 2023-02-24 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(choices=[('ECO', 'Эконом'), ('STA', 'Стандарт'), ('VIP', 'VIP')], db_index=True, max_length=3, verbose_name='вариант')),
                ('max_orders_number', models.PositiveSmallIntegerField(verbose_name='максимальное количество заказов')),
                ('fix_subcontractor_ability', models.BooleanField(default=False, verbose_name='возможность закрепить подрядчика')),
                ('get_contractor_contacts_ability', models.BooleanField(default=False, verbose_name='возможность увидеть контакты подрядчика')),
                ('order_review_period', models.PositiveSmallIntegerField(verbose_name='срок рассмотрения заказа (в часах)')),
            ],
            options={
                'verbose_name': 'тариф',
                'verbose_name_plural': 'тарифы',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begins_at', models.DateField(verbose_name='начинается с')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tgbot.client', verbose_name='клиент')),
                ('subcontractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='tgbot.subcontractor', verbose_name='подрядчик')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='tgbot.tariff', verbose_name='тариф')),
            ],
            options={
                'verbose_name': 'подписка',
                'verbose_name_plural': 'подписки',
            },
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('begins_at', 'client'), name='unique_subscription'),
        ),
    ]
