# Generated by Django 4.1.7 on 2023-02-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_tariff_subscription_subscription_unique_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_site_login',
            field=models.CharField(blank=True, max_length=20, verbose_name='логин сайта клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_site_password',
            field=models.CharField(blank=True, max_length=20, verbose_name='пароль сайта клиента'),
        ),
    ]
