# Generated by Django 4.1.7 on 2023-02-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_order_client_site_login_order_client_site_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_site_login',
            field=models.CharField(blank=True, editable=False, max_length=20, verbose_name='логин сайта клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_site_password',
            field=models.CharField(blank=True, editable=False, max_length=20, verbose_name='пароль сайта клиента'),
        ),
    ]
